name: Update README with Recent Activity

on:
  schedule:
    - cron: '*/5 * * * *' # actualiza cada 30 minutos, puedes cambiar el intervalo
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README with recent activity
      uses: gautamkrishnar/gh-actions-activity@v0.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        readme-path: README.md
        max-entries: 5
        exclude: 'WatchEvent,CreateEvent,DeleteEvent'
